### ISSUE TITLE
How can I install nvim packages?

### ISSUE THREAD

**Issue by metalelf0** [voitd/dotfiles#4]
Hey man!

I've seen your beautiful nvim config, and I'd love to use it as a starting point to build a new one for me - I'm still using a vimscript one, and I wanted to try a lua one, just to see how it works.

When I cloned your `.config/nvim` dir and started nvim, however, it complained about a missing file -- `lua/settings/packages.lua`, that should - as far as I understand - list the references to external packages needed by your config. Commenting that line results in `module 'gitsigns' not found`, so it seems there's some dependency missing. Could you please provide that file?

Thanks for sharing your config and keep up the great work!

**Comment by voitd** [comment]
Hey!

My bad! Didn't see this file missing on last commit. I just uploaded the latest actual configs and i hope it goes well with this attempt. Good luck with your setup!
