### ISSUE TITLE
Can't replicate your Nvim config

### ISSUE THREAD

**Issue by hrqmonteiro** [voitd/dotfiles#5]
I copied the files from the nvim folder to my .config, then i opened a file and started to install the plugins with Packer;

But the config is all strange, and the plugins won't install, and i got this error(s):

As soon as i open it:

![2021-03-07_00-47](https://user-images.githubusercontent.com/17055027/110228296-c2255c80-7ede-11eb-9b20-943bf3c5cf37.png)

Then if i press enter:

![2021-03-07_00-47_1](https://user-images.githubusercontent.com/17055027/110228298-c6ea1080-7ede-11eb-8279-d52a858506c7.png)
![2021-03-07_00-47_2](https://user-images.githubusercontent.com/17055027/110228299-c782a700-7ede-11eb-83df-6cacc749fda6.png)

Any help on it, please?

**Comment by voitd** [comment]
Hi @hrqmonteiro! 

I just updated the config to the current state, the errors should go away.

In the first screenshot, this is my mistake, I did not add the `tabbad.lua` file to `dotbare`. 

In the second screenshot, you need to run `:UpdateRemotePlugins` after install of the `ultest.lua` plugin. But in the last config variant, this plugin is no used, since the author broke something in the last update and it does not work for `js`.

**Comment by hrqmonteiro** [comment]
Hi, thanks for that!!

I am not used to use the nvim configs in lua, or using Packer or anything like that, so i couldn't handle it myself. Not i am very close to your config:

![2021-03-07_10-08](https://user-images.githubusercontent.com/17055027/110240967-24a54980-7f2d-11eb-9930-e03023e78c1e.png)

I am just having this error everytime i open nvim, you know how could i fix it?

![2021-03-07_10-07](https://user-images.githubusercontent.com/17055027/110240974-30910b80-7f2d-11eb-8655-99d27d272463.png)

**Comment by hrqmonteiro** [comment]
Also the completion engine is not quite the same as yours, could this be just the LSP problem?

![2021-03-07_10-14](https://user-images.githubusercontent.com/17055027/110241124-f5dba300-7f2d-11eb-9967-7230254db3e0.png)

Cause, actually, what caught my attention in your config was the screenshot of the completion, i like that very much. I was using plain Coc in my nvim config, and i liked your way better than mine.

**Comment by voitd** [comment]
@hrqmonteiro 

If you don't use vue in the work, you can just comment out these line:
https://github.com/voitd/dotfiles/blob/90556cc8aaa33c4f85d1b84a8d1b6e480da3eb89/.config/nvim/lua/lsp/init.lua#L20

**Comment by voitd** [comment]
@hrqmonteiro 

In the last screenshot, it looks like the `language servers` are not installed. They need to be installed manually. Look here:
https://github.com/neovim/nvim-lspconfig
or 
https://github.com/alexaandru/nvim-lspupdate

**Comment by hrqmonteiro** [comment]
I ultimately was able to set it right.

Could you maybe give me a little help in something. I also always used Nord as the colorscheme, but i can't enable the italics, bold and italic comments on it.

I setted it like you, in `nord.lua`:

```
local g = vim.g

g.nord_bold = 1
g.nord_italic = 1
g.nord_italic_comments = 1
g.nord_underline = 1
 ```

But it just don't activate it. Neither the bold nor the italic works. In your config is this working properly?

![2021-03-14_14-03](https://user-images.githubusercontent.com/17055027/111077138-22636200-84ce-11eb-9bd1-3f79032289d2.png)

I realized that the only way it works is if that i create a init.vim again and put it there in the vimscript way (like `let g:nord_bold`) and so on.

**Comment by voitd** [comment]
Hi @hrqmonteiro !

I'm glad everything worked out. 
Yes, sometimes I get the same bug, not only with the theme, but also with other plugins!
But I did not find a pattern, much less a way to correct this!

Plugin options work fine if you put them in this file:

`https://github.com/voitd/dotfiles/blob/master/.config/nvim/lua/settings/globals.lua`
